modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/jumpy-boats"
issueTrackerURL="https://github.com/JDKDigital/jumpboat/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="${mod_authors}"
    description='''${mod_description}'''

[[mixins]]
    config="jumpboat.mixin.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
